In [53]:
import pandas as pd
import requests
import io
    
# Downloading the csv file from what Kailin uploaded

url = "https://raw.githubusercontent.com/paulsizaire/paulsizaire.github.io/main/socioec_ECF.csv" # Make sure the url is the raw version of the file on GitHub
download = requests.get(url).content

# Reading the downloaded content and turning it into a pandas dataframe

df = pd.read_csv(io.StringIO(download.decode('utf-8')))

In [54]:
#looking at it 
df.FIPS.unique()

array([ 1001,  1003,  1005, ..., 56041, 56043, 56045])

In [55]:
# take only the columns with "TONCO2E"
emissions_cols = [col for col in df.columns if 'TONCO2E_' in col]
emissions_cols.append("FIPS")
df[emissions_cols]

,TONCO2E_AG_PERCENT,TONCO2E_CN_PERCENT,TONCO2E_COMM_PERCENT,TONCO2E_MF_PERCENT,TONCO2E_MN_REST_PERCENT,TONCO2E_PWR_PERCENT,TONCO2E_OG_PERCENT,TONCO2E_COAL_PERCENT,FIPS
0,0.393718,0.530985,2.460606,54.825715,0.169877,41.619100,0.000000,0.000000,1001
1,2.346790,6.949035,48.011126,32.104248,0.482742,0.000000,10.106060,0.000000,1003
2,4.442345,1.268463,8.028706,43.296743,42.963743,0.000000,0.000000,0.000000,1005
3,25.759659,21.771010,27.133636,8.359882,16.975813,0.000000,0.000000,0.000000,1007
4,34.159956,8.581610,32.259530,24.075403,0.923502,0.000000,0.000000,0.000000,1009
...,...,...,...,...,...,...,...,...,...
3135,0.047573,0.114289,0.175027,7.497172,54.646522,24.126708,11.123293,2.269416,56037
3136,6.701101,34.210390,43.641403,8.443043,0.866234,0.062608,6.075221,0.000000,56039
3137,1.197628,1.042005,1.880693,16.008788,0.516944,0.000000,78.855612,0.498330,56041
3138,10.492089,4.185477,2.874462,42.231148,11.526578,0.000000,28.690247,0.000000,56043
3139,4.161137,1.224335,1.594365,62.321807,5.303358,0.000000,25.394998,0.000000,56045

In [56]:
df[emissions_cols]

,TONCO2E_AG_PERCENT,TONCO2E_CN_PERCENT,TONCO2E_COMM_PERCENT,TONCO2E_MF_PERCENT,TONCO2E_MN_REST_PERCENT,TONCO2E_PWR_PERCENT,TONCO2E_OG_PERCENT,TONCO2E_COAL_PERCENT,FIPS
0,0.393718,0.530985,2.460606,54.825715,0.169877,41.619100,0.000000,0.000000,1001
1,2.346790,6.949035,48.011126,32.104248,0.482742,0.000000,10.106060,0.000000,1003
2,4.442345,1.268463,8.028706,43.296743,42.963743,0.000000,0.000000,0.000000,1005
3,25.759659,21.771010,27.133636,8.359882,16.975813,0.000000,0.000000,0.000000,1007
4,34.159956,8.581610,32.259530,24.075403,0.923502,0.000000,0.000000,0.000000,1009
...,...,...,...,...,...,...,...,...,...
3135,0.047573,0.114289,0.175027,7.497172,54.646522,24.126708,11.123293,2.269416,56037
3136,6.701101,34.210390,43.641403,8.443043,0.866234,0.062608,6.075221,0.000000,56039
3137,1.197628,1.042005,1.880693,16.008788,0.516944,0.000000,78.855612,0.498330,56041
3138,10.492089,4.185477,2.874462,42.231148,11.526578,0.000000,28.690247,0.000000,56043
3139,4.161137,1.224335,1.594365,62.321807,5.303358,0.000000,25.394998,0.000000,56045

In [57]:
df["FIPS"]=df["FIPS"].astype(int).astype(str)

In [58]:
emissions_df = df[emissions_cols].T.reset_index().rename({'index':'industry'},axis=1)
#
emissions_df

,industry,0,1,2,3,4,5,6,7,8,...,3130,3131,3132,3133,3134,3135,3136,3137,3138,3139
0,TONCO2E_AG_PERCENT,0.393718,2.34679,4.442345,25.759659,34.159956,13.154011,25.92593,2.04985,2.47878,...,19.847576,5.47077,0.771499,25.712467,0.283967,0.047573,6.701101,1.197628,10.492089,4.161137
1,TONCO2E_CN_PERCENT,0.530985,6.949035,1.268463,21.77101,8.58161,1.979818,6.275691,2.319868,2.854169,...,3.309417,3.301943,0.221877,12.980206,0.245333,0.114289,34.21039,1.042005,4.185477,1.224335
2,TONCO2E_COMM_PERCENT,2.460606,48.011126,8.028706,27.133636,32.25953,7.448334,29.416298,18.296579,14.690719,...,4.270709,3.597943,0.227764,24.389327,0.035837,0.175027,43.641403,1.880693,2.874462,1.594365
3,TONCO2E_MF_PERCENT,54.825715,32.104248,43.296743,8.359882,24.075403,77.417836,38.382081,72.000479,79.976333,...,0.105463,14.296371,0.067109,5.621257,0.059716,7.497172,8.443043,16.008788,42.231148,62.321807
4,TONCO2E_MN_REST_PERCENT,0.169877,0.482742,42.963743,16.975813,0.923502,0.0,0.0,0.784423,0.0,...,0.412402,0.798802,0.03945,3.305254,0.255102,54.646522,0.866234,0.516944,11.526578,5.303358
5,TONCO2E_PWR_PERCENT,41.6191,0.0,0.0,0.0,0.0,0.0,0.0,4.548801,0.0,...,0.0,0.0,98.672301,0.028675,0.0,24.126708,0.062608,0.0,0.0,0.0
6,TONCO2E_OG_PERCENT,0.0,10.10606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,72.054433,72.534172,0.0,27.962814,99.120045,11.123293,6.075221,78.855612,28.690247,25.394998
7,TONCO2E_COAL_PERCENT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.269416,0.0,0.49833,0.0,0.0
8,FIPS,1001,1003,1005,1007,1009,1011,1013,1015,1017,...,56027,56029,56031,56033,56035,56037,56039,56041,56043,56045

In [59]:
emissions_df.columns=emissions_df.iloc[8]
emissions_df.drop(8,inplace=True)

In [63]:
emissions_df["FIPS"] = ['Agriculture','Construction','Commercial','Manufacturing','Mining','Power','Oil and Gas','Coal']
emissions_df

8,FIPS,1001,1003,1005,1007,1009,1011,1013,1015,1017,...,56027,56029,56031,56033,56035,56037,56039,56041,56043,56045
0,Agriculture,0.393718,2.34679,4.442345,25.759659,34.159956,13.154011,25.92593,2.04985,2.47878,...,19.847576,5.47077,0.771499,25.712467,0.283967,0.047573,6.701101,1.197628,10.492089,4.161137
1,Construction,0.530985,6.949035,1.268463,21.77101,8.58161,1.979818,6.275691,2.319868,2.854169,...,3.309417,3.301943,0.221877,12.980206,0.245333,0.114289,34.21039,1.042005,4.185477,1.224335
2,Commercial,2.460606,48.011126,8.028706,27.133636,32.25953,7.448334,29.416298,18.296579,14.690719,...,4.270709,3.597943,0.227764,24.389327,0.035837,0.175027,43.641403,1.880693,2.874462,1.594365
3,Manufacturing,54.825715,32.104248,43.296743,8.359882,24.075403,77.417836,38.382081,72.000479,79.976333,...,0.105463,14.296371,0.067109,5.621257,0.059716,7.497172,8.443043,16.008788,42.231148,62.321807
4,Mining,0.169877,0.482742,42.963743,16.975813,0.923502,0.0,0.0,0.784423,0.0,...,0.412402,0.798802,0.03945,3.305254,0.255102,54.646522,0.866234,0.516944,11.526578,5.303358
5,Power,41.6191,0.0,0.0,0.0,0.0,0.0,0.0,4.548801,0.0,...,0.0,0.0,98.672301,0.028675,0.0,24.126708,0.062608,0.0,0.0,0.0
6,Oil and Gas,0.0,10.10606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,72.054433,72.534172,0.0,27.962814,99.120045,11.123293,6.075221,78.855612,28.690247,25.394998
7,Coal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.269416,0.0,0.49833,0.0,0.0

In [64]:
emissions_df.to_csv("ACS/emissions.csv")